cache_path: <?php echo DIR_FS_CATALOG?>web_cache/cjloader/
cache: true
cdn: true
# this option is not working yet
combine: false
load_global: true
load_loaders: true
supported_externals: ['http', 'https', '//']